name: Deploy Sphinx docs to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check for modifications in docs
      id: changed-docs
      uses: tj-actions/changed-files@v37
      with:
        files: docs/*

    - name: Setup Pages
      if: steps.changed-docs.outputs.any_changed == 'true'
      uses: actions/configure-pages@v3
    
    - name: Build HTML
      if: steps.changed-docs.outputs.any_changed == 'true'
      uses: ammaraskar/sphinx-action@master
      
    - name: Upload artifacts
      if: steps.changed-docs.outputs.any_changed == 'true'
      uses: actions/upload-pages-artifact@v1
      with:
        name: github-pages
        path: docs/build/html/
        
    - name: Deploy
      if: steps.changed-docs.outputs.any_changed == 'true'
      id: deployment
      uses: actions/deploy-pages@v2
