name: Lint and Syntax Check

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc clang cppcheck libgtk-3-dev gtk+-3.0 librsvg2-dev

      - name: Lint and Syntax Check
        run: |
          find . -name '*.c' | xargs gcc -Wall `pkg-config --cflags gtk+-3.0 librsvg-2.0 gio-unix-2.0 gio-2.0` -Wextra -pedantic -std=c17 -fsyntax-only `pkg-config --libs gtk+-3.0 librsvg-2.0 gio-unix-2.0 gio-2.0` -lm
          find . -name '*.c' | xargs clang -Wall `pkg-config --cflags gtk+-3.0 librsvg-2.0 gio-unix-2.0 gio-2.0` -Wextra -pedantic -std=c17 -fsyntax-only `pkg-config --libs gtk+-3.0 librsvg-2.0 gio-unix-2.0 gio-2.0` -lm
          find . -name '*.c' -o -name '*.h' | xargs cppcheck --enable=all --std=c11 --error-exitcode=1
