name: Lint and Syntax Check

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make gcc clang cppcheck libgtk-3-dev gtk+-3.0 librsvg2-dev

      - name: Lint and Syntax Check
        run: |
          make check